升级补丁增加脚本，支持删除文件并自动应用新文件；更新clientonlymodlist列表；将客户端、服务端、补丁的测试分支名独立，方便单独测试 (#415)

diff --git a/.github/workflows/release-patch.yaml b/.github/workflows/release-patch.yaml
--- a/.github/workflows/release-patch.yaml
+++ b/.github/workflows/release-patch.yaml
@@ -3,7 +3,7 @@ run-name: ${{ github.actor }} 正在发布补丁🚀
 on:
   push:
     branches:
-      - test-release
+      - test-patch
       - release
 
 jobs:
@@ -31,11 +31,9 @@ jobs:
       - name: 生成整合包nightly构建后缀
         id: set_version_prefix
         run: |
-          echo ${{ steps.read-modpackname.outputs.value }}
-          echo ${{ steps.read-version.outputs.value }}
-          if [[ $GITHUB_REF == refs/heads/test-release ]]; then
-            VERSION_SUFFIX=$(date +%m%d%H%M)
-            echo "VERSION_SUFFIX=-$VERSION_SUFFIX" >> $GITHUB_OUTPUT
+          if [[ $GITHUB_REF != refs/heads/release ]]; then
+            VERSION_SUFFIX="nighly-build-${{ github.run_number }}"
+            echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_OUTPUT
           else
             echo "VERSION_SUFFIX=" >> $GITHUB_OUTPUT
           fi
@@ -58,76 +56,116 @@ jobs:
           fi
           echo "最近的tag是: $latest_tag"
           echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
-      - name: 根据tag生成补丁
+      - name: Prepare patch files
         run: |
-          temp_dir=$(mktemp -d)
-          # 创建合并记录文件
-          mods_changes="$temp_dir/mods_changes.txt"
-          touch "$mods_changes"
+          # 生成完整差异报告
+          git diff --name-status ${{ env.LATEST_TAG }} HEAD > diff_report.txt
+          
+          # 解析差异报告
+          grep -E '^D' diff_report.txt | cut -f2 > deleted_files.txt
+          grep -E '^R' diff_report.txt | cut -f2 >> deleted_files.txt
+          grep -E '^[A|M]' diff_report.txt | cut -f2 > added_files.txt
+          grep -E '^R' diff_report.txt | cut -f3 >> added_files.txt
+          grep -E '^C' diff_report.txt | cut -f3 >> added_files.txt
 
-          # 获取所有有变化的文件及变化类型
-          git diff --name-status ${{ env.LATEST_TAG }} HEAD | while IFS=$'\t' read -r status file; do
-            echo "file: $file"
-            echo "status: $status"
-            if [[ $file == mods/* ]]; then
-              case $status in
-                A)
-                  echo "添加: $file" >> "$mods_changes"
-                  ;;
-                D)
-                  echo "删除: $file" >> "$mods_changes"
-                  ;;
-                R*)
-                  old_file=$(echo "$file" | cut -d$'\t' -f1)
-                  new_file=$(echo "$file" | cut -d$'\t' -f2)
-                  echo "升/降级: $old_file -> $new_file" >> "$mods_changes"
-                  ;;
-              esac
-            else
-              case $status in
-                A|M)
-                  if [ -e "$file" ]; then
-                    target_dir="$temp_dir/$(dirname "$file")"
-                    mkdir -p "$target_dir"
-                    cp -rL "$file" "$target_dir"
-                  fi
-                  ;;
-                R*)
-                  new_file=$(echo "$file" | cut -d$'\t' -f2)
-                  if [ -e "$new_file" ]; then
-                    target_dir="$temp_dir/$(dirname "$new_file")"
-                    mkdir -p "$target_dir"
-                    cp -rL "$new_file" "$target_dir"
-                  fi
-                  ;;
-                D)
-                  echo "文件 $file 已删除，跳过复制。"
-                  ;;
-              esac
-            fi
+          # 创建补丁目录
+          mkdir -p patch
+
+          # 复制新增/修改文件
+          while IFS= read -r file; do
+            mkdir -p "patch/$(dirname "$file")"
+            cp "$file" "patch/$file"
+          done < added_files.txt
+
+          # 移除客户端only的mod
+          mapfile -t prefixes < .clientonlymodlist
+          for prefix in "${prefixes[@]}"; do
+            echo "Deleting files with prefix: $prefix"
+            find patch/mods -name "${prefix}*" -exec rm {} +
           done
 
-          echo "PATCH_DIR=$temp_dir" >> $GITHUB_ENV
-      - name: 从生成的补丁临时目录里删除无用文件
+          # 移除无用文件
+          rm -f patch/ModList0.4a.md
+          rm -f patch/README.md
+          rm -f patch/TODOlist.md
+          rm -f patch/KubeJSStyleGuide.md
+          rm -f patch/DevGuide.md
+          rm -f patch/pack.toml
+          rm -f patch/index.toml
+          rm -f patch/client_jvm_args.example.txt
+
+      - name: Create Linux script
         run: |
-            # mapfile -t names < ${{ github.workspace }}/.packwizignore
-            # names+=("pack.toml")
-            # for filename in "${names[@]}"; do
-            #   echo "Deleting files $filename"
-            #   find ${{ env.PATCH_DIR }} -name "${filename}" -exec rm {} +
-            # done
-            rm -f ${{ env.PATCH_DIR }}/ModList0.4a.md
-            rm -f ${{ env.PATCH_DIR }}/README.md
-            rm -f ${{ env.PATCH_DIR }}/TODOlist.md
-            rm -f ${{ env.PATCH_DIR }}/KubeJSStyleGuide.md
-            rm -f ${{ env.PATCH_DIR }}/DevGuide.md
-            rm -f ${{ env.PATCH_DIR }}/pack.toml
-            rm -f ${{ env.PATCH_DIR }}/index.toml
-            rm -f ${{ env.PATCH_DIR }}/client_jvm_args.example.txt
+          cat << 'EOF' > deploy-patch.sh
+          #!/bin/bash
+          echo "Applying Patch..."
+          BASE_DIR=$(dirname "$(readlink -f "$0")")
+          
+          # files to be deleted
+          if [ -f "$BASE_DIR/deleted_files.txt" ]; then
+            while IFS= read -r line; do
+              if [ -f "$file" ]; then
+                rm -v "$file" || echo "Cannot delete $file"
+              fi
+            done < "$BASE_DIR/deleted_files.txt"
+          fi
+
+          # move patched files to right place
+          cp -r "patch" "."
+
+          # remove patch folder
+          rm -rf "patch"
+
+          echo -e "\n操作完成！"
+          EOF
+
+      - name: Create Windows script
+        run: |
+          cat << 'EOF' > deploy-patch.bat
+          @echo off
+          setlocal enabledelayedexpansion
+
+          rem files to be deleted
+          set "pathFile=deleted_files.txt"
+
+          rem Check if the file exists
+          if not exist "%pathFile%" (
+              echo File %pathFile% doesn't exist.
+              exit /b 1
+          )
+
+          rem read line by line and remove files
+          for /f "usebackq delims=" %%a in ("%pathFile%") do (
+              rem Convert Linux-style to Windows-style path
+              set "path=%%a"
+              set "path=!path:/=\!"
+              
+              rem Check if file exists and delete it
+              if exist "!path!" (
+                  echo Deleting: !path!
+                  del "!path!"
+                  if errorlevel 1 (
+                      echo Error when delete !path!
+                  )
+              ) else (
+                  echo File !path! doesn't exist.
+              )
+          )
+
+          rem move patched files to right place
+          xcopy /E /I /Y "patch" "."
+          rd /S /Q "patch"
+
+          endlocal
+          EOF
 
       - name: 上传补丁
         uses: actions/upload-artifact@v4
         with:
-          name: "[Patch]-${{ env.LATEST_TAG }}-to-${{ steps.read-version.outputs.value }}${{ steps.set_version_prefix.outputs.VERSION_SUFFIX }}"
-          path: ${{ env.PATCH_DIR }}
+          name: "[Patch]-${{ env.LATEST_TAG }}-to-${{ steps.read-version.outputs.value }}-${{ steps.set_version_prefix.outputs.VERSION_SUFFIX }}"
+          path: |
+            deleted_files.txt
+            deploy-patch.sh
+            deploy-patch.bat
+            patch/
       - run: echo "🍏 This job's status is ${{ job.status }}."
